### ISSUE TITLE
Enhancements to WIP PR

### ISSUE THREAD

**Issue by acchen97** [logstash-plugins/logstash-filter-jdbc_static#3]
After further discussion on the [WIP PR](https://github.com/logstash-plugins/logstash-filter-jdbc_static/pull/2) with @jordansissel @suyograo we've proposed the following changes to the JDBC static filter for initial delivery:

- For loaders and lookups, let's change these into an array of objects. For the loaders, let's instead have an explicit user defined id for each query (potential to tie metrics to them in the future). If no id specified, we can generate a random hash.
- We discussed adding a "target" field for each lookup with the default behavior being that all fields are automatically enriched at the event top level (instead of in a nested object currently).
- For consistent behavior with (2), let's also add a "local_table" option for each loader which specifies which table we're populating locally. This field should be required.
- Let's get rid of the before_sql_load and after_sql_load options. Although we're dealing with a SQL audience, it feels a bit much to require users to specify DDL for things like table/index creation. Can we instead auto-infer this stuff from the DB via the initial connection? The indices required for fast retrieval can also be inferred through the lookup query WHERE clause.
- Let's restrict (at least initially) a jdbc_static plugin instance to only allow for one JDBC connection. This will be a cleaner and more isolated, and if users desire to conduct cross DB joins, they can still do so with lookups via a subsequent jdbc_static instance against the new enriched fields.
- The "lookups" field should be changed to "local_lookups" to be more descriptive that it is querying from the local Derby DB.
- Lastly, if possible, we should add a top level option to limit memory consumption via this plugin to mitigate unwarranted OOM. i.e. max_memory => "2GB". This would be per plugin instance, not per table.

Here's a sample config with the proposed changes above:

```
filter {
  jdbc_static {
    jdbc_driver_library => …
    jdbc_driver_class => …
    jdbc_connection_string => …
    jdbc_user => …
    jdbc_password => ….
    max_memory => "2GB"
    refresh_schedule => ... # "refresh_schedule" is more descriptive than "schedule"

    # populate local cache from external db
    loaders => [
      {
        id => “country_details”,
        query => “SELECT code, name FROM WORLD.COUNTRY”,
        local_table => "country"
        max_rows => 2000
      },
      {
        id => “internal_servers”,
        query => “SELECT ip, name FROM INTERNAL.SERVERS”,
        local_table => "servers"
        max_rows => 1000
      }
    ]

    # lookup and enrich from local cache
    local_lookups => [
      {
        # no target = all new fields added to event top level
        query => "SELECT * FROM country WHERE code = :code",
        parameters => { "code" => "country_code" }
      },
      {
        # all fields go into target field as nested object
        query => "SELECT * FROM servers WHERE ip = :ip",
        parameters => { "ip" => "host_ip" },
        target => "enriched_fields"
      }
    ]
  }
}
```

**Comment by guyboertje** [comment]
- [x] _For loaders and lookups, let's change these into an array of objects..._ **NOTES: A random ID does not make sense as the user will not know which random ids have been associated with whick loader config. ID is optional**
- [x] _adding a "target" field for each lookup with the default behavior being that all fields are automatically enriched at the event top level (instead of in a nested object currently)..._
- [x] _For consistent behavior with (2), let's also add a "local_table" option for each loader which specifies which table we're populating locally. This field should be required..._
- [x] _Let's get rid of the before_sql_load and after_sql_load options. Although we're dealing with a SQL audience, it feels a bit much to require users to specify DDL for things like table/index creation. Can we instead auto-infer this stuff from the DB via the initial connection? The indices required for fast retrieval can also be inferred through the lookup query WHERE clause_ **NOTES: the free form SQL statements have been removed. However a hash like minimal db objects creation hash config called `local_db_objects` can be supplied and if it is, the db objects are created. See non in-memory db case below**
- [x] _The "lookups" field should be changed to "local_lookups" to be more descriptive that it is querying from the local Derby DB_
- [ ] _we should add a top level option to limit memory consumption via this plugin to mitigate unwarranted OOM. i.e. max_memory => "2GB". This would be per plugin instance, not per table_ **NOTES: After a brief discussion with the team, I will say its not really practical. OOM will appear before one has a chance to stop them and if we limit the number of records being retrieved or added then the lookup is not going to work SOME of the time**
- [x] _Let's restrict (at least initially) a jdbc_static plugin instance to only allow for one JDBC connection. This will be a cleaner and more isolated, and if users desire to conduct cross DB joins, they can still do so with lookups via a subsequent jdbc_static instance against the new enriched fields_
- [x] _Wildcard lookups on local cache - this would be challenging with a key/value hash, but as we're using Derby we can take advantage of "LIKE" statements_
- [x] _Allow the use of a file based, not in-memory, not local (not enforced) database via local_jdbc... config options. This allows a user to prepopulate a large database with as many tables and records as desired. This is similar to what the jdbc_streaming plugin can do but different in that it allows the user to do multiple lookups in one pass. In this mode loaders and local_db_objects should not be supplied_

**Comment by guyboertje** [comment]
@acchen97 
What do you think of [my comment on the PR](https://github.com/logstash-plugins/logstash-filter-jdbc_static/pull/2#issuecomment-349924895)?

The handling of @target is the only deviation from these discussions that is material to the docs you are writing.

**Comment by acchen97** [comment]
@guyboertje answered in the PR. I'm good with your proposal.

**Comment by guyboertje** [comment]
PR merged, closing.

**Comment by acchen97** [comment]
@guyboertje good work on this one! :+1:
