### ISSUE TITLE
Can't get scheduler syntax correct

### ISSUE THREAD

**Issue by thekofimensah** [logstash-plugins/logstash-filter-jdbc_static#8]
I've tried

loader_schedule => ["0 * * * *"]
loader_schedule => "0 * * * *"
loader_schedule => [0 * * * *]

which all lead to a different error of sorts. The documentation mentions it should be a string and that's about it. An example would be great!

**Comment by jakelandis** [comment]
@guyboertje - I believe that this is a bug , I couldn't get the configuration to work either and I don't see how the existing code could work.

```
[2018-02-11T14:57:17,269][ERROR][logstash.filters.jdbcstatic] Invalid setting for jdbc_static filter plugin:

  filter {
    jdbc_static {
      # This setting must be a [LogStash::Filters::Jdbc::LoaderSchedule]
      # The options must be an Array
      loader_schedule => "0 * * * *"
      ...
    }
  }
```

**Comment by ermik** [comment]
Documentation has the `loader_scedule` setting at level 1 of filter config next to `loaders`, `local_db_objects`, `local_lookup`, etc. Just as well it uses the canonical `string` setting, which raises an error:
```logs
elastic.logs     | filter {
elastic.logs     |     jdbc_static {
elastic.logs     |       # This setting must be a [LogStash::Filters::Jdbc::LoaderSchedule]
elastic.logs     |       # The options must be an Array
elastic.logs     |       loader_schedule => "*/10 * * * *"
elastic.logs     |       ...
elastic.logs     |     }
elastic.logs     |   }
```
*Can* be fixed by moving the `loader_schedule` setting into the specific loader, as described in various literature... and by literature I mean comments on the web
