### ISSUE TITLE
Use-case: if statement for null fields in document

### ISSUE THREAD

**Issue by thekofimensah** [logstash-plugins/logstash-filter-jdbc_static#9]
In my use case, the ingested event is defined by a _user_id_. I do a lookup on my MySQL db to get all columns in the db with that matching _user_id_. This works fine.

However, there are instances where the _user_id_ is null and I need to use another, less specific id in the ingested event called _geo_id_. I only want to use _geo_id_ when my _user_id_ is missing, but never use _geo_id_ when there is a _user_id_. I can do this just fine with 2 if statements with the jdbc_static filter in each. I'm wondering if there is a built in way to do this or if this functionality makes sense to add. I would imagine having the filter twice would mean there are 2 identical db in the cache which isn't very efficient. 
Is it possible to not define the loaders and local_db_objects in the second if statement and just include the local_lookups object? Any ideas?

**Comment by guyboertje** [comment]
Based on what you are saying the `geo_id` is a kind of user.
I would do this in Logstash, have an if conditional block before the jdbc_static filter that creates a new field called, say, `event_user_id` that is either the `user_id` or `geo_id` and then do the lookup on `lookup_user_id` (it acts as a local variable on programming terms).
```
  # if the user_id id numeric, use the line below
  # if [user_id] and [user_id] > 0 {
  if [user_id] and [user_id] != "" {
    mutate {
      copy => { "lookup_user_id" => "user_id" }
    }
  } else {
    mutate {
      copy => { "lookup_user_id" => "geo_id" }
    }
  }
```

In terms of if conditionals being defined inside a filters settings block - this is not possible because the grammar does not allow it. The settings block is passed in-toto to the plugin's initialization mechanism where validations are done and the plugin is readied for execution.

However a slightly different semantic could be followed if two lookups are defined on the same target where the first lookup finds no records only then is the second lookup attempted.

**Comment by guyboertje** [comment]
@seanziee FYI ⬆️

**Comment by thekofimensah** [comment]
@guyboertje Thanks for the answer. Yeah, I've set it up so that logstash will use the conditionals to guide the document to the right place, but it just feels like a waste to have the same table saved twice in the catch (with a different lookup). My document has a user_id pointing to a column in SQL called id and geo_id pointing to a column in the same table called geo_id. So I need to change the lookup destination field also which the logstash fix wouldn't do (as far as my brain can understand it) 

Thanks for the response though!
